import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-staffing-agency-bill-rate-audit",
  "engine": "recovery",
  "title": "Staffing Agency Bill-Rate Audit",
  "shortTitle": "Staffing Agency Bill-Rate Audit",
  "tagline": "Audit contingent labor invoices across pay rates, markups, overtime, tenure discounts, conversions, and expenses.",
  "industry": "Contingent Labor Cost Recovery",
  "buyer": "Enterprise HR and procurement teams",
  "uiPort": 4726,
  "apiPort": 5726,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Staffing Agency Bill-Rate Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits in one accountable workflow. Audit contingent labor invoices across pay rates, markups, overtime, tenure discounts, conversions, and expenses.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Staffing Agency Bill-Rate Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("staffing-agreement-library","SAB01","Staffing agreement library","Execute staffing agreement library using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed staffing agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Staffing agreement library Reference","text","SAB01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("worker-assignment-registry","SAB02","Worker assignment registry","Execute worker assignment registry using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed worker assignment registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Worker assignment registry Reference","text","SAB02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("approved-pay-rate-control","SAB03","Approved pay rate control","Execute approved pay rate control using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed approved pay rate control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Approved pay rate control Reference","text","SAB03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("markup-calculation","SAB04","Markup calculation","Execute markup calculation using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed markup calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Markup calculation Reference","text","SAB04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("timecard-ingestion","SAB05","Timecard ingestion","Execute timecard ingestion using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed timecard ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Timecard ingestion Reference","text","SAB05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("overtime-rate-validation","SAB06","Overtime rate validation","Execute overtime rate validation using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed overtime rate validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Overtime rate validation Reference","text","SAB06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("holiday-premium-audit","SAB07","Holiday premium audit","Execute holiday premium audit using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed holiday premium audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Holiday premium audit Reference","text","SAB07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("tenure-discount-tracking","SAB08","Tenure discount tracking","Execute tenure discount tracking using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed tenure discount tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Tenure discount tracking Reference","text","SAB08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("conversion-fee-calculation","SAB09","Conversion fee calculation","Execute conversion fee calculation using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed conversion fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Conversion fee calculation Reference","text","SAB09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("expense-policy-validation","SAB10","Expense policy validation","Execute expense policy validation using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed expense policy validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Expense policy validation Reference","text","SAB10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("duplicate-worker-billing","SAB11","Duplicate worker billing","Execute duplicate worker billing using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed duplicate worker billing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Duplicate worker billing Reference","text","SAB11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("invoice-recalculation","SAB12","Invoice recalculation","Execute invoice recalculation using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Invoice recalculation Reference","text","SAB12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("agency-dispute-workflow","SAB13","Agency dispute workflow","Execute agency dispute workflow using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed agency dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Agency dispute workflow Reference","text","SAB13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("credit-reconciliation","SAB14","Credit reconciliation","Execute credit reconciliation using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Credit reconciliation Reference","text","SAB14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]}),
feature("agency-role-analytics","SAB15","Agency role analytics","Execute agency role analytics using staffing agreements, requisitions, workers, pay rates, markups, timecards, overtime, holidays, conversions, expenses, invoices, and credits.","Produce a governed agency role analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Worker Assignment","text","Agency / Worker Assignment · Standard Case"],["caseReference","Agency role analytics Reference","text","SAB15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1648750],["supportedAmount","Evidence-Supported Amount","currency",1384950],["domainDriver","Worker Class","select","Temporary",["Temporary","Contractor","Temp-to-hire"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Staffing agreement library case","Worker assignment registry case","Approved pay rate control case","Markup calculation case","Timecard ingestion case"]})
]);
